### ISSUE TITLE
New source - Reddit / imgur [Herekt]

### ISSUE THREAD

**Issue by RobbWatershed** [RobbWatershed/GalleryCherry#15]
Support for reddit

~~**Manual mode**~~ (dropped)
~~open the subreddit~~
~~see some images posted by someone in imgur~~
~~open the imgur link~~
~~download button appears => download all in that album~~

**Saved mode**
- Open the "saved" folder of your profile
- The download button appears => download everything in a single "Reddit saved" album

- [x] imgur.com
- [x] i.redd.it

**Comment by herdidi47** [comment]
for reddit source, since there is a lot of reddit nsfw, make it custom so the user can put any subreddit that they want. 

> reddit.com/r/nsfw as example where nsfw is the subreddit

![ui example](https://user-images.githubusercontent.com/11810021/62004028-23ede400-b14a-11e9-9e21-cdd90b05e541.png)

for enchantment, make history section like below

![ui example enchantment](https://user-images.githubusercontent.com/11810021/62004044-408a1c00-b14a-11e9-9032-b06303e24748.png)

**Comment by RobbWatershed** [comment]
IMGUR API : https://apidocs.imgur.com/?version=latest

**Comment by RobbWatershed** [comment]
REDDIT API : https://www.reddit.com/dev/api
